name: example
check_this_dir: /etc/alpine-release
grub_prepare:
    - chroot||apk add grub grub-bios grub-efi
    - echo 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash rw modules=sd-mod,usb-storage,ext4"' >> /target/etc/default/grub
grub_installation_efi: chroot||grub-install --target=x86_64-efi --force {disk}
grub_installation_legacy: chroot||grub-install --target=i386-pc --force {disk}
run_before_user_creation:
    - echo uwu
additional_mountpoints:
    - /home
additional_efi_mountpoints:
    - /boot/efi
