name: debian
check_this_dir: /etc/debian_version
grub_prepare:
    - bash scripts/fetch-pkg-debian.sh
grub_installation_efi: chroot||grub-install --bootloader-id={distro_codename} --force {disk}
grub_installation_legacy: chroot||grub-install --force {disk}
run_before_user_creation: 
   - echo "Creating users"
additional_mountpoints:
    - /home
    - /boot
    - /tmp
    - /var
    - /srv
additional_efi_mountpoints:
    - /boot/efi
