name: example
check_this_dir: /etc/example_version
grub_prepare:
    - echo uwu
grub_installation_efi: echo uwu
grub_installation_legacy: echo uwu
run_before_user_creation:
    - echo uwu
additional_mountpoints:
    - /home
additional_efi_mountpoints:
    - /boot/efi
