// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.donation.eoy.version.viewed", 7);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1734460138);
user_pref("app.update.lastUpdateTime.region-update-timer", 1734460138);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1734460138);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1734460167);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1734460138);
user_pref("browser.display.document_color_use", 2);
user_pref("browser.display.use_system_colors", true);
user_pref("calendar.caldav.googleResync", 1734460110);
user_pref("calendar.list.sortOrder", "ba07b83e-7110-4b56-8112-ece1649043c5");
user_pref("calendar.registry.ba07b83e-7110-4b56-8112-ece1649043c5.calendar-main-default", true);
user_pref("calendar.registry.ba07b83e-7110-4b56-8112-ece1649043c5.calendar-main-in-composite", true);
user_pref("calendar.registry.ba07b83e-7110-4b56-8112-ece1649043c5.disabled", true);
user_pref("calendar.registry.ba07b83e-7110-4b56-8112-ece1649043c5.name", "Home");
user_pref("calendar.registry.ba07b83e-7110-4b56-8112-ece1649043c5.type", "storage");
user_pref("calendar.registry.ba07b83e-7110-4b56-8112-ece1649043c5.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "America/Recife");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1734460120032");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20241125170630");
user_pref("extensions.lastAppVersion", "128.5.0");
user_pref("extensions.lastPlatformVersion", "128.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/theme");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"2fe8828a-c0f9-4227-9b26-d0865f4589c5\"}");
user_pref("font.name.sans-serif.x-western", "Quicksand");
user_pref("font.size.variable.x-western", 12);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.inline_attachments", false);
user_pref("mail.nstmp_cleanup_completed", true);
user_pref("mail.pane_config.dynamic", 0);
user_pref("mail.quoted_size", 2);
user_pref("mail.rights.version", 1);
user_pref("mail.ui-rdf.version", 46);
user_pref("mail.uidensity", 0);
user_pref("mail.uifontsize", 12);
user_pref("mailnews.database.global.datastore.id", "b2fcb4aa-9996-4604-998c-9c90e16f6e2");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "128.5.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("msgcompose.font_face", "Quicksand");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("toolkit.startup.last_success", 1734461460);
user_pref("toolkit.telemetry.cachedClientID", "204aa2f0-2467-4ad5-942d-6e29a9e68101");
user_pref("toolkit.telemetry.previousBuildID", "20241125170630");
