// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1734459589);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1734459589);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1734459589);
user_pref("app.update.lastUpdateTime.region-update-timer", 1734459589);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1734459589);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1734459618);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1734459589);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{0d1c0383-5851-4f32-9ee2-8fe8ad5954d3}");
user_pref("browser.display.background_color", "#deddda");
user_pref("browser.display.document_color_use", 2);
user_pref("browser.display.use_system_colors", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.firefox-view.view-count", 1);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1734459560);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 148);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{95c740ad-c47c-489c-a57f-3c2c29c06741}");
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20241128151741");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1734460098");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage", "https://google.com");
user_pref("browser.startup.homepage_override.buildID", "20241128151741");
user_pref("browser.startup.homepage_override.mstone", "128.5.1");
user_pref("browser.startup.lastColdStartupCheck", 1734460098);
user_pref("browser.tabs.inTitlebar", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":20,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1734459562757");
user_pref("distribution.iniFile.exists.appversion", "128.5.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.formautofill.creditCards.reauth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECNpNkHjQYHJiBAiz52jJDvs6bQ==");
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20241128151741");
user_pref("extensions.lastAppVersion", "128.5.1");
user_pref("extensions.lastPlatformVersion", "128.5.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/theme");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"9b304291-ade4-4dce-adfe-e22817549721\",\"pictureinpicture@mozilla.org\":\"a8e27b40-323b-4147-92a6-09aae2591076\",\"screenshots@mozilla.org\":\"b2bd9a4f-31fb-4054-8470-ca399871a1f1\",\"webcompat-reporter@mozilla.org\":\"263b4271-b8af-443d-b2c3-be1ca11ca66c\",\"webcompat@mozilla.org\":\"dadac03c-3eae-405f-ac6d-05e35b160097\",\"default-theme@mozilla.org\":\"a2edd47f-8dba-4b95-9550-4898adc7c8b4\",\"addons-search-detection@mozilla.com\":\"bae54d5a-154a-4e5a-ad07-c6a0b83324a9\",\"firefox-compact-dark@mozilla.org\":\"50e44403-f537-4c39-895b-3ad5a94d43eb\"}");
user_pref("font.name.monospace.x-western", "Quicksand");
user_pref("font.name.sans-serif.x-western", "Quicksand");
user_pref("font.name.serif.x-western", "Quicksand");
user_pref("font.size.variable.x-western", 12);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.lastDownloadFailReason", "Error: Failed downloading via ServiceRequest, status: 0, channelStatus: 2152398878, errorCode: 2, reason: error");
user_pref("media.gmp-gmpopenh264.lastDownloadFailed", 1734459589);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1734459589);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearHistory.siteSettings", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs2", true);
user_pref("privacy.sanitize.cpd.hasMigratedToNewPrefs2", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "b372c1d4-477b-4832-a444-a35f9898205d");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("signon.management.page.os-auth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECPZauAPOIotRBAhE3aYdf8l6Aw==");
user_pref("toolkit.startup.last_success", 1734460097);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20241128151741");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.key.menuAccessKeyFocuses", false);
